### ISSUE TITLE
[Bug] Losing modifers after going through end portal

### ISSUE THREAD

**Issue by x1msoc** [Hempflingclub/Immortality-Fabric#9]
**Describe the bug**
Losing heart/armor/armor toughness modifer after going through end portal
**To Reproduce**
Get some Armor Toughness by dying as True Immortal, go through end portal (in the end dimension)

**Expected behavior**
They should stay

**Screenshots / Logs**
https://user-images.githubusercontent.com/87891239/228647989-069cc87e-ea61-468e-a965-93246be243ad.mp4

**Used Mod Version**
v1.1.1-1.19.2

**Comment by Hempflingclub** [comment]
As it seems Heart / Armor Modifiers were unaffected in the clip. However the Command did report the armor toughness to have vanished.
This was resolved before by a periodic check once every 10 seconds to counteract these sudden changes, mostly by the end portal. Now they will also be forcefully done upon using any immortality command.

Could you test, whether this resolved the issue, so I can push this release?
[immortality-1.1.2-1.19.2.zip](https://github.com/Hempflingclub/Immortality-Fabric/files/11117801/immortality-1.1.2-1.19.2.zip)

**Comment by x1msoc** [comment]
> As it seems Heart / Armor Modifiers were unaffected in the clip. However the Command did report the armor toughness to have vanished.
> This was resolved before by a periodic check once every 10 seconds to counteract these sudden changes, mostly by the end portal. Now they will also be forcefully done upon using any immortality command.
> 
> Could you test, whether this resolved the issue, so I can push this release?
> [immortality-1.1.2-1.19.2.zip](https://github.com/Hempflingclub/Immortality-Fabric/files/11117801/immortality-1.1.2-1.19.2.zip)

Okay, I'll test it as soon as I arrive home.
Also, I think this issue may be related to this: https://bugs.mojang.com/browse/MC-181604
Recently I made mod to fix this, but it isn't published yet

**Comment by Hempflingclub** [comment]
> > As it seems Heart / Armor Modifiers were unaffected in the clip. However the Command did report the armor toughness to have vanished.
> > This was resolved before by a periodic check once every 10 seconds to counteract these sudden changes, mostly by the end portal. Now they will also be forcefully done upon using any immortality command.
> > Could you test, whether this resolved the issue, so I can push this release?
> > [immortality-1.1.2-1.19.2.zip](https://github.com/Hempflingclub/Immortality-Fabric/files/11117801/immortality-1.1.2-1.19.2.zip)
> 
> Okay, I'll test it as soon as I arrive home. Also, I think this issue may be related to this: https://bugs.mojang.com/browse/MC-181604 Recently I made mod to fix this, but it isn't published yet

Yeah it's because when using the End Portal, internally you don't technically teleport to the Overworld, it is more like your Player is 'cloned' to the Overworld and this process is only retaining some of your data, thus losing status effects and modifiers.

If only that is the issue, it should now be resolved, as I've combated the NBT save retention with Cardinal Components. So this likely only needs reapplication on the End Portal usage, which should be done by an Event, but I'm not sure how to get an 'used End Portal' event, so I'm using this roundabout way.

Let me know, if the update resolved the issue.

**Comment by Hempflingclub** [comment]
As there has been no Feedback, I presume 1.1.2-1.19.2 has fixed the issue
